join_key: id 
input:
  table:
    - name: ./input.csv
    #  columns:
    #    - id
    #    - name
    #    - price
    - name: ./input2.csv
    #  columns:
    #    - id
    #    - kind
    #    - taste_score
output:
  table:
    - name: ./output.csv
      columns:
        - id
        - name
        - kind
        - price
        - taste_score
